version: '3.9'

services:
# ============================================================
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}


# ============================================================
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    


  